"""Column filter definitions for the Skolereg external API."""

VARIABELER = [
    "rectype",
    "org_nr",
    "fnr",
    "bnr",
    "orgnrbed",
    "flv",
    "fkommune",
    "status_foretak",
    "aktivitetskode",
    "org_form",
    "navn",
    "off_nav1",
    "off_nav2",
    "karakt",
    "status",
    "nace1_sn07",
    "nace2_sn07",
    "nace3_sn07",
    "sektor_2014",
    "undersektor_2014",
    "delreg_merke",
]
